package liuyang.testclient.modules.webservice.soap.cxf.stub01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2022-04-19T09:23:25.383+08:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://services.server.modules.testcxf.liuyang/", name = "HelloInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloInterface {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://services.server.modules.testcxf.liuyang/", className = "liuyang.testclient.modules.webservice.soap.cxf.stub01.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://services.server.modules.testcxf.liuyang/", className = "liuyang.testclient.modules.webservice.soap.cxf.stub01.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(

        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "foo", targetNamespace = "http://services.server.modules.testcxf.liuyang/", className = "liuyang.testclient.modules.webservice.soap.cxf.stub01.Foo")
    @ResponseWrapper(localName = "fooResponse", targetNamespace = "http://services.server.modules.testcxf.liuyang/", className = "liuyang.testclient.modules.webservice.soap.cxf.stub01.FooResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String foo()
;
}
